### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by tmkch** [tmkch/FANDOM-Monaco#18]
Implement a way to alter Monaco themes.

**Comment by unai01** [comment]
Could be done by adding extension options:
- https://developer.chrome.com/extensions/options
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page

**Comment by tmkch** [comment]
@unai01 
Editor window has access to user-set window variables (those from `global.js` etc.), so we can just tell the user to pass theme config in something like `window.monacoTheme`. That would probably be an easier solution.
